#define WHITE FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY

#define RED FOREGROUND_RED | FOREGROUND_INTENSITY
#define BLUE FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define GREEN FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define RED_BOX BACKGROUND_RED | FOREGROUND_RED | FOREGROUND_INTENSITY | BACKGROUND_INTENSITY
#define WHITE_BOX BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY

#define BLACK 0

#define D_BULLET_MAX 50
#define D_ENEMY_MAX 50
#define D_EFFECT_MAX 50
